# Generated by Django 2.0.7 on 2018-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180711_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
