# Generated by Django 2.0.7 on 2018-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userprofile_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='userdps/'),
        ),
    ]
