# Generated by Django 2.0.7 on 2018-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180718_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, default='defautl.png', null=True, upload_to='userdps/'),
        ),
    ]
